apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: external-dns
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:Ld6Bbri4n+PS0P2pqO9i6EkzpGnpJuCDXs9vTlvnWPSmotSV5i4+UHvzaRR/9qdCpWVeGWs=,iv:S6M2tWNTx9nvXuPOnEEQswxVjU7ngz1U3fxzdAVBiIc=,tag:gjOk/3Xu6AnlgO98LX019A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCR2NZT21Ma09aeHZrZUYv
            L0NrK3dSWmRUaUN3ZG5jYTJuUzV5bUtyc3k0ClVkK2VYNCt5dFA3N0IyOWU3ZnEr
            UHVWTkJjOFZQZ2lLSEVKRHZGb0ZLeW8KLS0tIGRKT2l2T0JZNXVHdEpJWG1JVVNa
            ZGoyWTkxRlN1Qm1PSTNJTnhxWWdxK2MKrDi9OnFMzeaTb1Gid4bktL0bIoN0q9P8
            60gxfFTMG3m5H3kc46IidEdlYHGtiWZlqD9I/lHsBNvMTB92I1s25Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1y93vgmxvlrvv4kw5q32qqcf7tftqkrm2qzmcg00zka080nsazdjqn7k5m8
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-14T20:41:22Z"
    mac: ENC[AES256_GCM,data:zFezB7RpHFTDzo2IKv7jwg4H/FKo7972iRt8o7Q2Uv2pVYfv8ZYWbkg51bYMe2sMpzQNMBjhVaBL5VGmkAVfO8rYuLSQ3DWmoI+6GBSsDf2xj9SPuhXKFzNA791tEtqHDpq0Z0jNhz5pe31VqPsSWaEaLQ+UQ8ILUyZLcdjxgcU=,iv:MJnNnPsl+EZxUsIDvnDqCIOX+MgYwqmpp9pRsSsC9pg=,tag:y9WUyOrgzE72bqydrih8xg==,type:str]
    version: 3.13.0
