---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: gateway
spec:
  encryptedData:
    api-token: AgAT0rwss/o/cc+DMw/fQajf+2EGx9shknyR9bp4568pyxvBfXUhz775jwNagnMXjqCG66xfj5HX6m/hcNNeXAOSmRsj/ji2WMsqIsA08nZweYxOemgfDFAITOHKrbYFNiaIZIYZ6M3RUAV1bRC29INlu3ftwGVpcHDEfoVUC1Lk3wYqSkic7rn7cK8QpI8hVTcUyx+aeW5FzB188shF4FIrqe56YuDWJx+TkrqWwd8daG6LOGq4JDZoPo7F6UU45gPHwNO8H33ih98LhzcXWSFYWae9BvgMcULVPpz87O8OXVEHHtBG2GF37Ad8g9NCa8/QDohJBrc/tIZU4TwYqzTtE18GYHa6ytuVsmLG8xkv+Zn/f7jfPtbCmtMl/DSGgHgdbA9BbWGswyEfy0UKJYRJN16xa/wwomlhm5SXNHkK180ZUVX5P53zdoelQrQ8zQs4RCzWZAxfKvtveGBwizF5OpJ549itfHIcV5SsChtEUGGKHemTsgg+SDf8/nC9RWgvE1W/rmBoeQ+PDsQY8osoDBCX+88NkkU/FwA+ofyM045snCfS38akn84YI8JmRUiNL+W5DECSk5TMQiDpPShAyxIA1XNI8Pmz1bfTTJO1KvMTZfMlTXv+bHiXVbT9Btv1QDLlA4bLJPukBDXhVGralgwszc6z9Si77EB+eDqpuIfSKe0eAV52B/b0RKFlInWmvIzhaIQhhmClgi0H66J7/+QqMv0ukVTo4WFdioT6fmG7jhVvG5jR
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: gateway
