# yaml-language-server: $schema=https://goauthentik.io/blueprints/schema.json
# Group definitions. Membership is left to the database — blueprints
# create the groups but don't try to enumerate users.
version: 1
metadata:
  name: Groups
entries:
  - model: authentik_core.group
    identifiers:
      name: "authentik Admins"
    attrs:
      is_superuser: true

  - model: authentik_core.group
    identifiers:
      name: "authentik Read-only"
    attrs:
      is_superuser: false

  - model: authentik_core.group
    identifiers:
      name: "public services"
    attrs:
      is_superuser: false
