apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vault-unseal

resources:
  - namespace.yaml

helmCharts:
  - name: vault
    repo: https://helm.releases.hashicorp.com
    version: "0.30.0"
    releaseName: vault-unseal
    namespace: vault-unseal
    valuesFile: values.yaml
