all:
  children:
    pve_hosts:
      hosts:
        lenovo-01:
        lenovo-02:
        lenovo-03:
  vars:
    ansible_user: root
    ansible_port: 22
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
