apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  namespace: argocd
  name: infrastructure
  labels:
    app.kubernetes.io/part-of: infrastructure
    app.kubernetes.io/managed-by: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '-10'
spec:
  generators:
    - git:
        repoURL: https://github.com/leonvdbeek/homelab.git
        revision: master
        directories:
          # - path: k8s/argocd
          # - path: k8s/cert-manager
          # - path: k8s/cilium
          # - path: k8s/gateway
          - path: k8s
  template:
    metadata:
      name: 'infra-{{ path.basename }}'
      namespace: argocd
      labels:
        app.kubernetes.io/component: 'static-infrastructure'
        app.kubernetes.io/part-of: infrastructure
    spec:
      project: infrastructure
      source:
        repoURL: https://github.com/leonvdbeek/homelab.git
        targetRevision: master
        path: '{{ path }}'
        kustomize: {} # Let Kustomize handle naming
      destination:
        namespace: infrastructure-system
        server: https://kubernetes.default.svc
      syncPolicy:
        # automated:
        #   prune: true
        #   selfHeal: true
        retry:
          limit: 1
          backoff:
            duration: 10s
            factor: 2
            maxDuration: 3m
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
          - ServerSideApply=true
          - PruneLast=true
          - RespectIgnoreDifferences=true