apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- cert-manager
- cilium
- gateway
- https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.30.0/controller.yaml