apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: longhorn-system

resources:
  - ns.yaml
  # - recurringjob.yaml
  - http-route.yaml
  # - externalsecret.yaml

helmCharts:
  - name: longhorn
    namespace: longhorn-system
    releaseName: longhorn
    repo: https://charts.longhorn.io
    valuesFile: values.yaml
    version: 1.8.2 # renovate: github-releases=longhorn/longhorn