apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: postgres-operator

resources:
  - ns.yaml

helmCharts:
  - name: postgres-operator
    repo: https://opensource.zalando.com/postgres-operator/charts/postgres-operator
    version: v1.14.0
    releaseName: zalando
    namespace: postgres-operator
    valuesFile: values.yaml
    includeCRDs: true
  # - name: postgres-operator-ui
  #   repo: https://opensource.zalando.com/postgres-operator/charts/postgres-operator-ui
  #   version: v1.14.0
  #   releaseName: zalando
  #   namespace: postgres-operator
  #   # valuesFile: values.yaml
  #   includeCRDs: true
generatorOptions:
  disableNameSuffixHash: true