apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/cert-manager/cert-manager/releases/download/v1.18.0/cert-manager.crds.yaml # renovate: https://charts.jetstack.io
  - ns.yaml

helmCharts:
  - name: cert-manager
    repo: https://charts.jetstack.io
    version: v1.18.1 # renovate: github-releases=jetstack/cert-manager
    releaseName: cert-manager
    namespace: cert-manager
