apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/cert-manager/cert-manager/releases/v1.17.2/download/cert-manager.crds.yaml # renovate: https://charts.jetstack.io
  - ns.yaml

helmCharts:
  - name: cert-manager
    repo: https://charts.jetstack.io
    version: 1.13.3 # renovate: github-releases=jetstack/cert-manager
    releaseName: cert-manager
    namespace: cert-manager
    valuesInline:
      crds.enabled: true
