# Cloudflare API token consumed by the ClusterIssuer's DNS-01 solver.
# Same Cloudflare token used by external-dns (separate copy in that
# namespace — we don't share Secrets across namespaces).
#
# Edit, then encrypt:
#   sops -e -i kubernetes/cert-manager/secret.enc.yaml   (after rename)
# To rotate:
#   sops kubernetes/cert-manager/secret.enc.yaml         (in-place edit)
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:CRHilHmjHspnLpqKRQwtiM+sNGbMH9X23gPuT7tIFsC9+I4j06kHNRyX77X/Jpo5A3eZyaI=,iv:ZcNaOHMKaTSmktkhrlTVpbj2Y7X77WLamdI2sijnOac=,tag:ghs0ceS2XDXsARUdk+Htkw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHaGxjWG5pbWhGYnN1NHFx
            a1doWGFKNUJua0lDaTlHMk1QdUplc2k0VjFrCmplT3Z5V2Z1alRMU2dkbE9xWXpm
            dVBvTU5NRzJyYXlubEdPdXMraFBPc2sKLS0tIFUvVFUxa05Cb2JwbzJzdHhhSUkz
            MkpucThmcUFtUEt3Qng2Q0FaVmZvTTgKmkQayIJ+9zqMlswSqkhmyRNqKzvrsoSC
            HJ8k1I+KFz2Ol5maU2RTMxu2HRm6ZVxBFaL8A29o1pLzcySCQpuMjQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1y93vgmxvlrvv4kw5q32qqcf7tftqkrm2qzmcg00zka080nsazdjqn7k5m8
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-14T20:40:40Z"
    mac: ENC[AES256_GCM,data:0aSAE8dcqJ8Fh0szfeVXlpV0iR1i4Dk623h1X+wIV0gjVJvLKwwFsQK2NQk3HPxrPiOuNPDd6uEJKFpCPZqfmsAJZtzLKKEBmpnqH9LcFwVO43GB4qkBPckSGvOx+XEyj9iYJ6kZSzK1a7+kmM8krO8WHIJbU7uduqAjXeKdjtI=,iv:fCh2G6NiWEP9FMiYtrAtzF7kBm56Kb0Hwxm4ujt+bPI=,tag:+IY2yemsiQnWinCyzi/ICA==,type:str]
    version: 3.13.0
