apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-local-leonvdbeek-com
  namespace: gateway
spec:
  dnsNames:
    - "*.local.leonvdbeek.com"
    - "*.gateway.local.leonvdbeek.com"
  issuerRef:
    name: cloudflare-issuer
    kind: Issuer
    group: cert-manager.io
  secretName: cert-local-leonvdbeek-com
  usages:
    - digital signature
    - key encipherment