apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-kube-leonvdbeek-com
  namespace: gateway
spec:
  dnsNames:
    - "*.lenovium.leonvdbeek.com"
    - "lenovium.leonvdbeek.com"
  issuerRef:
    name: cloudflare-issuer
    kind: Issuer
    group: cert-manager.io
  secretName: cert-kube-leonvdbeek-com
  usages:
    - digital signature
    - key encipherment