apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: gateway
spec:
  encryptedData:
    api-token: AgCAuBkSMVdt1uKTs0Jr2Lm2UuOJ9PfCB0jkDCSldu843+uBcqwYZXOMTCak5IGFgFU1cfkG41pxIFdGO7oFWkJOrx3pQvv4mfXrg6yp/Z9U7wMLW9Z9pQ/a79d2+Dz8JwGH3mXZ97jN5o4gUpGV0dfwzPeNtQMJTTpFLoILeY/sFq7LgEsxckMUyNB4TdzLwwKntx9i1gEm/sBaE6xL93HAkTPlziHg6X7LXiXkIIai1qistqGgwXkidEkbvS6WPWRxGKGOTmFItB26FJo7vrqJak8hc3VskIWMhgna+mWw6dYFXEyQ6UWjwJb1wVrO5Osv7LQi49vJJk1REN8mMuxFcUNhbxNq41dT0j7mdo8QUxKKxs90QZn+pdEIT3f/WkEllNORU7iQJ60qFnwIN0WSgaHjq3xuDWKqAOMZ++b4KSXIK5Vb3OMSa8zzCjQUtehpYjSdwDl0yqM5+mU/RGvJ7DMWimMxLTui++EArWIZMrcHF0atXv+0Pn6uAjwoEtkK4Ib3rsu5hZtmI0PXinvP1RfXAGJohef7BqR++ULg7ifusg2crwZUhMJEXX9HZtaDC4WRsUtw92F8qKR+4+UV0tKPrgoICH4Lee0ngMJOgwIxIksIyVM1fOQ1FLcvpkabd4GOGBdWDgYHHfjwqBCXkvRKioTii7LoGDLnQqA3ggS2WHW65fmwG9l5WHVOANL/tgnJMM5gIKR29wSgQl0x9Y7E/OTRM0d0u565NGVk3sKp2mDhIr0X
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: gateway
