---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: gateway
spec:
  encryptedData:
    api-token: AgCKBPiEr0MO7ylnhUn7juzzEBGOmCiYsf108E1v/FwrMc8kDg5RO8gyNdu+n8QDVhLFmvG4KdhT3zYpuSmHuNQvDWbkBpUhCJaW8yqrTdmHsIFYbJ4cZiH0lmc2+TQlQ1fpd5zxlVjP+d+3+MrYBLul/wgaVW84Yv+TxPKDpWbsj5lOGG7xJdQsKwcTkv0pZbeydrHqRKOUDXNKBiUBTzx31NB46FS9jUdZGS50GHxoYUYimrzHKmpjwm5HGbtDFx4AT79DFXVofW9pczsVevy65CC/w07RKU4HwnmcQ7+efM/aL+72Wf/kZOhjuLeYf8wCfPVMOa868h3TR8jxQOtdoJWSW1ApZxYpvRa52bE4QiYL3YhAw/XjkzU0z+TmA8At25m98uvZueqINFewys4SMS8NbI+CWpHwbENnOWFAv+YIQaTA8iMG9T37bVOY4OygNfLOQkEUx0juUolYV1BCm1XFUfpR9ATbZLDdb/mM1TZZC+880ccFAZkLF2Op86sNbOMb8iJwCgYbFWkhVPC9UyYF1+8y1vrMfGGh2CmewVKSv4M+S8wi4Chkaxn46ImJUmawd78xnPSfPOBF+cOwVUGvJsMp1lgu621H4WeCmjbKmtWPAUndSaOYnPoqhPwTZhuusT59gyAh8S/iR3c/YCgjOvOEyRkBOx9zlaGriZbca0H1pXk/ZUpljCmplxUt+Jfq/DYfMk4zkqdG+azV30q8mM7NECaWlQDYvxLjASfSAuOuwwDq
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: gateway
