---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: gateway
spec:
  encryptedData:
    api-token: AgAsFIPubGDVeWYsHzDXsavKWLOwWGgK810jXFSmiMItCTj90AA8Xq6vfz+9tm5yRE+thhtZ+ekrten5rXIkEagZ6YlFYxvRCOyFJeww1KC4bVsn3ZYddIsVWtgWBZBZ7kCRO39inNlD/w3s4Q+dl1HmKiXpXiHhdQcsPw4CYpvE44A+Ebr1KfRT22zj5PAFR+u6YZwOvMr2SExaotr0lh3pkzZecb5L7+ORc8dwgO7PyCXPy3OFTU1H7jXCZMLJEolP2Pl3Ss4NUdTq+6ygEqIgrMNw8kAU0CDTVbTSRmzEbAx3Vn8KvQinQ8tOEU8JbdlWn8lPQ7rMF3PnaNaTNZHSb+8oXwhypdhmW1nBiEKAfEH2Mo4o5lD9mrw1CsYaQDN8x5WdvomILCf9CXeSHi4ryeNkUcOHOyYvIqg//AUn53VzlPIX2YLX7qS5njPGeyLZXD2+pCgKKE4ViO83OECLNVwOkdTasZKGH8IOLpi9sfQ0YwKN98qDIvKoGsiIdg6Slit5gJWhM7BAU7XYrk6L0eMQEfX+Tc9wibVDN9lXnGTkPFAuTO8M0/wMDME/PuKl6QyDgHOyoQGvPw7sBHB7pdDb9SvwueHAQ66S8Bij8HwcS1NUAj67dUCLtrmE9GxKm+Se22yEBuryaSktaYwRWnXr1fQo4jzdsQl15XK7IFunLtSqsdNFQ8qbv+WfulPaKALyiQK2ZJts02hRuXhfwZy1ctkts4+Zw1PFR9vUBn+31EsvGxAn
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: gateway
