apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: cilium-gateway
  namespace: gateway
  annotations:
    cert-manager.io/issuer: cloudflare-issuer
spec:
  gatewayClassName: cilium
  infrastructure:
    annotations:
      io.cilium/lb-ipam-ips: "192.168.4.11"
  listeners:
    - protocol: HTTPS
      port: 443
      name: https-gateway
      hostname: "*.local.leonvdbeek.com"
      tls:
        certificateRefs:
          - kind: Secret
            name: cert-local-leonvdbeek-com
      allowedRoutes:
        namespaces:
          from: All
    - protocol: HTTPS
      port: 443
      name: https-domain-gateway
      hostname: "local.leonvdbeek.com"
      tls:
        certificateRefs:
          - kind: Secret
            name: cert-local-leonvdbeek-com
      allowedRoutes:
        namespaces:
          from: All