apiVersion: v1
kind: Secret
metadata:
    name: authentik-db
    namespace: postgres
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:6H+gc/94Oeup,iv:hdD4BNNpkk96X6NfVyjb428xN3R4ZnSskBmYAIqkOag=,tag:S5uE7zsyzX5lonarGvL++A==,type:str]
    password: ENC[AES256_GCM,data:2kvMt5IAv8N6kq+knMNb+nFId0NBcdXJGR9AbWKIXH8=,iv:VsnCEPIaHecHVN+7rtsXQ8BFH3zW6tCHMbAlNeu5a9o=,tag:e/YfXxWtbgdyRBLf1im7xw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxZjBtVUh1TCtDa0dlaGR5
            aGpWVjZKNUcyNCtRRHlpRTVrc3NLTkhleVM4CjhVN0Ewb2ZwaElvY290eHFSY3Ux
            YVRGU25wMXhkSTBCQU9WRzZaaVpRSTgKLS0tIDkwRFVUNEhBRzdzWXFMZHJyczlF
            SERiSitMVkgrQVhpWVM5WTZQRzNDRzQKuIIUPY+04kjXEsU4TNlJLoMVx5IpkQG/
            FKjv8JW7vKEOvLRD8raKzUc2UnVW5rSbwxBJBj3u1bNmpXaBZtKGjQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1y93vgmxvlrvv4kw5q32qqcf7tftqkrm2qzmcg00zka080nsazdjqn7k5m8
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-14T21:00:54Z"
    mac: ENC[AES256_GCM,data:tqYIMF1/B5etrlmzpcFQYhbxnCWxRUO3dhnhmzkYoo4h1VMnbLrZ5nL0IdcmZhxp/hvS/IeKNzuDZa9pswagZi48yAD1S8kj24gNtAem/LoO8DNzHYu7zjWEcYh+O4ACjzy7jJeYY68Lt1DL0TL1GP/aaFTfvcnmh6kzkFbh1Ps=,iv:KX0MutZbP//4kHOtcXdlmzbVrbBat+KQTAkKeVqLFo0=,tag:NXdPevMvhfQw4f9VgGCqXA==,type:str]
    version: 3.13.0
