apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - http-route.yaml

helmCharts:
- name: argo-cd
  namespace: argocd
  releaseName: argocd
  repo: https://argoproj.github.io/argo-helm
  valuesFile: values.yaml
  version: 8.1.0 # renovate: github-releases=argoproj/argo-helm