apiVersion: v1
kind: Secret
metadata:
    name: operator-oauth
    namespace: tailscale
type: Opaque
stringData:
    client_id: ENC[AES256_GCM,data:mfFRTMOIxhjQHbGx5Xm0Xew=,iv:5aG1mTR1T0qq9wioUQZFRVsZgTYnmbkKFuUSUMfkmZk=,tag:mBlKWvq5bWkhouixqKBwWw==,type:str]
    client_secret: ENC[AES256_GCM,data:djGUm6dGHOyq3mZAt8ZFAIB2YF0nDRhvWrweIIuJvpAxqPqPrEYR8SXqlPAC23nlkcNe3/o5KhWao2GkbCcK,iv:AwUmt/jwbGRtL+HeyW2ClsZtwDpOqCdTbK4u70iFfDg=,tag:MbGq/D1ERZdoDEhYcKNDFA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvYStvU1BpTi8zYzVMTW4z
            UXpFODN6U29QMWVyamxZaVdRUkpUeFpFS0VNCmhSdlB2ZTlNR0k3ZU1wUkUvU1c2
            UU1mY09BS3dha0J2MWh3SFY0SjJ6UGsKLS0tIDJZdmJ5ZFlOdXREcnV4cW44aS9F
            ODQxNFdWazIxUytMSTFieW5tVXdaQk0KOMbSMHIotaGfuTo4pvWyUCEYoZDOGTrC
            MLTWeTWJuO9mq0q2dPsY+KFJE7qz04NO8a/SmKI6ikTH83EU5X4VlQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1y93vgmxvlrvv4kw5q32qqcf7tftqkrm2qzmcg00zka080nsazdjqn7k5m8
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-15T11:16:02Z"
    mac: ENC[AES256_GCM,data:T/TA9IZQo+lxkzb/mKszQvRPVNqEJ78FeUw3q8FXMObjCavIj5Ul80X3KhG7UScFYLS+76duA6uIXpOrUZmQMdhRCAB7hPe6i2aOH8hBGdIl/1kEWtX++lxHTDoX+NWcuGJZ2xsd4mwY4u5Ej6BU8PYK579KgYvPkP5VtJjSOiQ=,iv:bQGtlRCghYAhjk8u9WTLbHuRMZy898ii2XGJlJTS7Tw=,tag:2iZNbi0Q8SmAjnZ+nUHnoA==,type:str]
    version: 3.13.0
