apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ceph-csi-cephfs

resources:
  - namespace.yaml
  - storageclass.yaml
  - externalsecret.yaml
  # `csi-cephfs-secret` materialized by ESO from Vault path
  # `kv/ceph-csi-cephfs/csi-cephfs-secret`.

helmCharts:
  - name: ceph-csi-cephfs
    repo: https://ceph.github.io/csi-charts
    version: "3.13.0"
    releaseName: ceph-csi-cephfs
    namespace: ceph-csi-cephfs
    valuesFile: values.yaml
