apiVersion: v1
kind: Secret
metadata:
    name: vault-transit-token
    namespace: vault
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:D8LJzoxGqoE5JOn1rSgIQ8GQZW7PzT7dHqwwruL9FgdN3TG9SGB1RngyXJMAbm+H0j1SrB7ABuKK53K6/rqznMYfSRpFLCqJka2PbEkPzUBi0yjv8Ck0Lz0cW6UBDEg=,iv:73t3c981hzKz1xUIN7CMEnF1fCxhw2srWFap+TzyrjQ=,tag:dxVJe4OlM3IHtqpiIp4cIw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyWmRaR1h0R1dOOFRsVkFF
            NGxPZHJiV1RUVmhlV1VvZytBYUU0Mk1wNGlZCmE2bU1HRklmdWR4TzMydS9kSHZk
            SS8yZm1QNEJWTVV3RDN4bWVycGtCSDAKLS0tIGRIaWFqWmQ0WnljRGsrYWJjaDRt
            MS9yL3NRU1U3M2tQUHV2eG8wNHRGdUkK0kP4VdmbAm7hS6aWprjCT63zX624mSyX
            jZWZS4adSKVV8T7riX543XBMcMN202wVcHkR5URyvBAluwPDD23BDw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1y93vgmxvlrvv4kw5q32qqcf7tftqkrm2qzmcg00zka080nsazdjqn7k5m8
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-19T05:52:42Z"
    mac: ENC[AES256_GCM,data:LQOU5FpCudFcVSR4K43QI0BjjgeAEpCP2pFDM2RDDcDFkDDT0jXNfTN/NzOvW6/69u3ETRGASi01TNFbAZ/GcYYD+OmWDrOxJE63GBpHXve7lVamJizg2SmkLhTHB8gnPQFxSBctKKSPQwFEKONcW5vxiNuH9RglxZ338nGuoMw=,iv:G0aKLZB5dzXRncpFidLJ5DPRviRAS+wN0kcQEOILFUE=,tag:qnTIlMh1nhG6rDzJzo08ZQ==,type:str]
    version: 3.13.0
