apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-core-secrets
  namespace: auth
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-backend
  target:
    name: authentik-core-secrets
    creationPolicy: Owner
  data:
    # --- Authentik Secret Key ---
    # Changed from 'secret-key' to 'AUTHENTIK_SECRET_KEY' for env var usage
    - secretKey: AUTHENTIK_SECRET_KEY
      remoteRef:
        key: 'app-authentik-secret-key'

    # --- Redis Password ---
    - secretKey: redis-password
      remoteRef:
        key: 'app-authentik-redis-password'

    - secretKey: AUTHENTIK_REDIS__PASSWORD
      remoteRef:
        key: 'app-authentik-redis-password'
    # --- Bootstrap Credentials ---
    - secretKey: AUTHENTIK_BOOTSTRAP_TOKEN
      remoteRef:
        key: 'app-authentik-bootstrap-token'
    - secretKey: AUTHENTIK_BOOTSTRAP_PASSWORD
      remoteRef:
        key: 'app-authentik-bootstrap-password'
    - secretKey: AUTHENTIK_BOOTSTRAP_EMAIL
      remoteRef:
        key: 'app-authentik-admin-email'